# Generated by Django 4.2.2 on 2023-07-03 00:36

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_slug_alter_module_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to=courses.models.rename_image_course),
        ),
    ]
