# Generated by Django 4.2.2 on 2023-07-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='creer_par',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='date_added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='auteur',
            new_name='owner',
        ),
    ]
