# Generated by Django 4.2.2 on 2023-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_available_course_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
