# Generated by Django 4.2.2 on 2023-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
